apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod-demo
  labels:
    name: liveness-pod-demo
spec:
  containers:
  - name: liveness-pod-demo
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 90
    args:
      - /bin/sh
      - -c
      - touch /tmp/healthy; sleep 30; #rm -rf /tmp/healthy; sleep 600
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
    livenessProbe:
      exec:
        command:
        - cat 
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5



