apiVersion: v1
kind: Pod
metadata:
  name: declarative-pod
  labels:
    name: declarative-pod
    pod: updated
spec:
  containers:
  - name: declarative-pod
    image: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    
