apiVersion: v1
kind: Pod
metadata:
  name: init-containers
  labels:
    name: init-containers
spec:
  containers:
  - name: init-containers
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
    volumeMounts:
      - name: workdir
        mountPath: /usr/share/nginx/html
  # these containers are run before the app containers and during pod initialization
  initContainers:
    - name: install-container
      image: busybox
      command:
        - wget
        - "-o"
        - "work-dir/index.html"
        - http://kubernetes.io
      volumeMounts:
        - name: workdir
          mountPath: "/work-dir"
  volumes:
    - name: workdir
      emptyDir:
        {}
