apiVersion: batch/v1
kind: Job
metadata:
  name:  pi
spec:
  template:
    metadata:
      name:  pi-job
    spec:
      containers:
      - name: job-container
        image: perl
        command: ["perl", "Mbignum=bpi", "-wle","print bpi(2000)"]
      restartPolicy: Never
      # backoffLimit: 4