apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://localhost:6443
  name: docker-for-desktop-cluster
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://34.83.27.211:6443
  name: kubernetes-the-hard-way
contexts:
- context:
    cluster: docker-for-desktop-cluster
    user: docker-for-desktop
  name: docker-for-desktop
- context:
    cluster: kubernetes-the-hard-way
    user: admin
  name: kubernetes-the-hard-way
current-context: kubernetes-the-hard-way
kind: Config
preferences: {}
users:
- name: admin
  user:
    client-certificate: /Users/suhaspothedar/Desktop/Computer Science/kubernetes/kubernetes-the-hard-way/admin.pem
    client-key: /Users/suhaspothedar/Desktop/Computer Science/kubernetes/kubernetes-the-hard-way/admin-key.pem
- name: docker-for-desktop
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
